/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simpledicegame;

import java.awt.Image;
import java.util.Random;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author SagarGi
 */
public class PlayGame extends javax.swing.JFrame {

    /**
     * Creates new form PlayGame
     */
    public PlayGame() {
        initComponents();
        scaleDefaultImage();
    }
    
    public void scaleDefaultImage()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\defaultdice.jpg");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }
    
    public void scaleImageOne()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\one.gif");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }
    public void scaleImageTwo()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\two.gif");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }
    public void scaleImageThree()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\three.gif");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }
    public void scaleImageFour()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\four.gif");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }
    
    public void scaleImageFive()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\five.gif");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }
    
    public void scaleImageSix()
    {
        ImageIcon imageicon = new ImageIcon("src\\diceimages\\six.gif");
        Image image = imageicon.getImage();
        Image imagescale = image.getScaledInstance(imagejlabel.getWidth(),imagejlabel.getHeight(),image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imagescale);
        imagejlabel.setIcon(scaledimage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        imagejlabel = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        rolldice = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        imagejlabel.setBackground(new java.awt.Color(255, 255, 255));

        mainLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainLabel.setText("Your Point is :");

        points.setForeground(new java.awt.Color(255, 255, 255));
        points.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        points.setText("0");

        rolldice.setBackground(new java.awt.Color(255, 255, 255));
        rolldice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        rolldice.setForeground(new java.awt.Color(0, 0, 0));
        rolldice.setText("Roll Dice");
        rolldice.setActionCommand("Roll Dice");
        rolldice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolldiceActionPerformed(evt);
            }
        });

        result.setForeground(new java.awt.Color(255, 0, 0));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("Back");
        back.setActionCommand("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagejlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rolldice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(result, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(points, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(imagejlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rolldice, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rolldiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolldiceActionPerformed

        int rand_int1, rand_int2;
        if(rolldice.getText() == "Roll Dice")
        {
            rolldice.setText("Roll Again");
            Random rand = new Random();
            rand_int1 = rand.nextInt(6);
            points.setText(String.valueOf(rand_int1 + 1));
            mainLabel.setText("First Point : ");
            switch(rand_int1)
            {
                case 0 : scaleImageOne();
                break;
                
                case 1 : scaleImageTwo();
                break;
                
                case 2 : scaleImageThree();
                break;
                
                case 3 : scaleImageFour();
                break;
                
                case 4 : scaleImageFive();
                break;
                
                case 5 : scaleImageSix();
                break;
                
                default:                 
                
            }
            
            
        }
        
        else if(rolldice.getText() == "Roll Again")
        {
            
            Random rand = new Random();
            rand_int2 = rand.nextInt(6);
            points.setText(String.valueOf((rand_int2 + 1) + Integer.parseInt(points.getText())));
            mainLabel.setText("Final Point : ");
            switch(rand_int2)
            {
                case 0 : scaleImageOne();
                break;
                
                case 1 : scaleImageTwo();
                break;
                
                case 2 : scaleImageThree();
                break;
                
                case 3 : scaleImageFour();
                break;
                
                case 4 : scaleImageFive();
                break;
                
                case 5 : scaleImageSix();
                break;
                
                default:                 
                
            }
            
            if(Integer.parseInt(points.getText()) == 7)
            {
                result.setText("You Win!!");
                result.setForeground(Color.GREEN);
                
            }
            else
            {
                result.setText("You Loose!!");
               
            }
            rolldice.setEnabled(false);
            back.setText("Play Again");
        }
        
       
    }//GEN-LAST:event_rolldiceActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if(back.getText() == "Back")
        {
            this.dispose();
            MainFrame mf = new MainFrame();
            mf.setVisible(true);
        }
        else if(back.getText() == "Play Again")
        {
            scaleDefaultImage();
            result.setText("");
            back.setText("Back");
            mainLabel.setText("Your Point is :");
            points.setText("0");
            rolldice.setEnabled(true);
            rolldice.setText("Roll Dice");
        }
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayGame().setVisible(true);
                imagejlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diceimages/one.gif")));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private static javax.swing.JLabel imagejlabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel points;
    private javax.swing.JLabel result;
    private javax.swing.JButton rolldice;
    // End of variables declaration//GEN-END:variables
}
